name: Master Build
'on':
  push:
    branches:
      - master
jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      version: '${{ steps.bump.outputs.version }}'
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v2
      - name: Bump Version
        id: bump
        uses: Plugily-Projects/version-bump-action@v6
        with:
          github-token: '${{ secrets.github_token }}'
          git-username: Maven-Version-Bot
          auto-version-bump: true
      - name: Print Version
        run: 'echo ''New Version: ${{steps.bump.outputs.version}}'''
  build:
    needs: bump
    outputs:
      version: '${{  needs.bump.outputs.version }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: 19
      - name: Build with Maven
        run: 'mvn -B clean:clean package --file pom.xml'
      - run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar
  release:
    if: 'contains(github.event.head_commit.message, ''#'')'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: jar
      - name: Display structure of downloaded files
        run: ls -R
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: '${{ needs.build.outputs.version }}'
          prerelease: false
          title: 'Version: ${{ needs.build.outputs.version }}'
          files: |
            **/*.jar
            README.md
  upload:
    runs-on: ubuntu-latest
    needs: release
    if: false
    steps:
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: jar
      - name: Glob match
        uses: tj-actions/glob@v16
        id: glob
        with:
          files: |
            *.jar
      - name: Show all matching files
        run: |
          echo "${{ steps.glob.outputs.paths }}"
      - name: Rename Jar
        run: mv ${{ steps.glob.outputs.paths }} MinecraftEmergency.jar
      - name: Publish to pterodactyl
        uses: Avenze/pterodactyl-actions@master
        with:
          panel: '${{ secrets.PANEL }}'
          api_key: '${{ secrets.API_KEY }}'
          server: '${{ secrets.SERVER }}'
          path: 'MinecraftEmergency.jar'
          directory: /plugins
      - name: Pterodactyl Power Action
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: '${{ secrets.PANEL }}'
          server-id: '${{ secrets.SERVER }}'
          bearer-token: '${{ secrets.API_KEY }}'
          power-action: restart
  prerelease:
    needs: build
    if: '!contains(github.event.head_commit.message, ''#'')'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v2
        id: download
        with:
          name: jar
      - name: Display structure of downloaded files
        run: ls -R
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            **/MinecraftEmergency-*.jar
            README.md
  mvnRelease:
    needs: release

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Latest Commit
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
